package chatting;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormAdmin extends javax.swing.JFrame {

    public UserModel user;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    Koneksi DB;
    public FormAdmin(UserModel user) {
        initComponents();
        this.user = user;
        DB = new Koneksi();
        DB.init();
        con = DB.conn;
        stat = DB.stm;
        setVisible(true);
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void getData(){
        DefaultTableModel modelPesan = (DefaultTableModel)msgtb_admin.getModel();
        DefaultTableModel modelUser = (DefaultTableModel)userTable.getModel();
        try {
                sql = "SELECT * FROM pesan";
                rs = stat.executeQuery(sql);
                modelPesan.setRowCount(0);
                while(rs.next()){                    
                    modelPesan.addRow(new Object[]{rs.getInt("id"),rs.getString("pengirim"),rs.getString("penerima"),rs.getString("pesan"), rs.getString("tanggal")});
                }
                
                sql = "SELECT * FROM user WHERE status="+"'"+0+"'";
                rs = stat.executeQuery(sql);
                modelUser.setRowCount(0);
                while(rs.next()){                    
                    modelUser.addRow(new Object[]{rs.getInt("id"),rs.getString("nama"),rs.getString("email"),rs.getString("pass"), "user"});
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }
    
    public void hapus_pesan(){
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete Record Ini???",
            "Confirmation",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            try{
                String sql="DELETE FROM pesan WHERE id='"+msgtb_admin.getValueAt(msgtb_admin.getSelectedRow(), 0)+"'";
                PreparedStatement state=con.prepareStatement(sql);
                state.executeUpdate();
                getData();
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
    }
    
    public void hapus_user(){
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete Record Ini???",
            "Confirmation",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            try{
                String sql="DELETE FROM user WHERE id='"+userTable.getValueAt(userTable.getSelectedRow(), 0)+"'";
                PreparedStatement state=con.prepareStatement(sql);
                state.executeUpdate();
                getData();
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpane_admin = new javax.swing.JTabbedPane();
        pnl_admin = new javax.swing.JPanel();
        scrlpane_admin = new javax.swing.JScrollPane();
        msgtb_admin = new javax.swing.JTable();
        lblMessage_admin = new javax.swing.JLabel();
        btn_deletepesan = new javax.swing.JButton();
        pnl_user = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_deleteuser = new javax.swing.JButton();
        pnl_send = new javax.swing.JPanel();
        lblMessageTo_admin = new javax.swing.JLabel();
        lblMessage2 = new javax.swing.JLabel();
        recipientTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageTextField = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpane_admin.setBackground(new java.awt.Color(51, 204, 255));
        tbpane_admin.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        msgtb_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "From", "To", "Message", "Date"
            }
        ));
        scrlpane_admin.setViewportView(msgtb_admin);

        lblMessage_admin.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        lblMessage_admin.setForeground(new java.awt.Color(51, 0, 102));
        lblMessage_admin.setText("Message");

        btn_deletepesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_deletepesan.setForeground(new java.awt.Color(51, 0, 102));
        btn_deletepesan.setText("Delete");
        btn_deletepesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletepesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_adminLayout = new javax.swing.GroupLayout(pnl_admin);
        pnl_admin.setLayout(pnl_adminLayout);
        pnl_adminLayout.setHorizontalGroup(
            pnl_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminLayout.createSequentialGroup()
                .addGroup(pnl_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_adminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrlpane_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(pnl_adminLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblMessage_admin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_deletepesan)))
                .addContainerGap())
        );
        pnl_adminLayout.setVerticalGroup(
            pnl_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_adminLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnl_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deletepesan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMessage_admin))
                .addGap(9, 9, 9)
                .addComponent(scrlpane_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpane_admin.addTab("Message", pnl_admin);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Password", "Status"
            }
        ));
        jScrollPane2.setViewportView(userTable);

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setText("User");

        btn_deleteuser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_deleteuser.setForeground(new java.awt.Color(51, 0, 102));
        btn_deleteuser.setText("Delete");
        btn_deleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_userLayout = new javax.swing.GroupLayout(pnl_user);
        pnl_user.setLayout(pnl_userLayout);
        pnl_userLayout.setHorizontalGroup(
            pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userLayout.createSequentialGroup()
                .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_userLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(pnl_userLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_deleteuser)))
                .addContainerGap())
        );
        pnl_userLayout.setVerticalGroup(
            pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpane_admin.addTab("User", pnl_user);

        lblMessageTo_admin.setText("Message To :");

        lblMessage2.setText("Message :");

        messageTextField.setColumns(10);
        messageTextField.setRows(5);
        jScrollPane3.setViewportView(messageTextField);

        sendBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(51, 0, 102));
        sendBtn.setText("Send");
        sendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBtnMouseClicked(evt);
            }
        });
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_sendLayout = new javax.swing.GroupLayout(pnl_send);
        pnl_send.setLayout(pnl_sendLayout);
        pnl_sendLayout.setHorizontalGroup(
            pnl_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sendLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnl_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendBtn)
                    .addGroup(pnl_sendLayout.createSequentialGroup()
                        .addGroup(pnl_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMessageTo_admin)
                            .addGroup(pnl_sendLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblMessage2)))
                        .addGroup(pnl_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_sendLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recipientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_sendLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnl_sendLayout.setVerticalGroup(
            pnl_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_sendLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMessageTo_admin)
                    .addComponent(recipientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnl_sendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendBtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tbpane_admin.addTab("Send", pnl_send);

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 102));
        jLabel5.setText("Welcome Admin");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 102));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tbpane_admin)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(tbpane_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
        LocalDateTime now = LocalDateTime.now(); 
        String from = user.getNama();
        String message = messageTextField.getText();
        String to = recipientTextField.getText();
        String date = dtf.format(now).toString();
        
        try{
            sql = "INSERT into pesan(pengirim, penerima, pesan, tanggal) VALUES (" + "'" +from+ "'" + "," + "'" +to+ "'" + "," + "'" +message+ "'" + "," + "'" +date+ "'"+")";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Message Sent Successfully");
            getData();
            recipientTextField.setText(null);
            messageTextField.setText(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void sendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sendBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        JOptionPane.showMessageDialog(this, "You'l be Logout !");
        FormLogin l = new FormLogin();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_deletepesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletepesanActionPerformed
        hapus_pesan();
    }//GEN-LAST:event_btn_deletepesanActionPerformed

    private void btn_deleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteuserActionPerformed
        hapus_user();
    }//GEN-LAST:event_btn_deleteuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deletepesan;
    private javax.swing.JButton btn_deleteuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMessage2;
    private javax.swing.JLabel lblMessageTo_admin;
    private javax.swing.JLabel lblMessage_admin;
    private javax.swing.JTextArea messageTextField;
    private javax.swing.JTable msgtb_admin;
    private javax.swing.JPanel pnl_admin;
    private javax.swing.JPanel pnl_send;
    private javax.swing.JPanel pnl_user;
    private javax.swing.JTextField recipientTextField;
    private javax.swing.JScrollPane scrlpane_admin;
    private javax.swing.JButton sendBtn;
    private javax.swing.JTabbedPane tbpane_admin;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
