package chatting;


import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class FormLogin extends javax.swing.JFrame {

    String username;
    String password;
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    Koneksi DB;
    UserModel user;
    
    public FormLogin(String greeting) {
        initComponents();
        JOptionPane.showMessageDialog(null, greeting);
        DB  = new Koneksi();
        DB.init();
        con = DB.conn;
        stat = DB.stm;
        user = new UserModel();
    }
    public FormLogin(){
        initComponents();
        DB  = new Koneksi();
        DB.init();
        con = DB.conn;
        stat = DB.stm;
        user = new UserModel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        pnl_login = new javax.swing.JPanel();
        lbl_login = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        lbl_password = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_login.setBackground(new java.awt.Color(51, 204, 255));
        pnl_login.setForeground(new java.awt.Color(0, 255, 255));
        pnl_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_login.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(51, 0, 102));
        lbl_login.setText("Chatting App");
        pnl_login.add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 190, -1));

        lbl_username.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        lbl_username.setText("Username :");
        pnl_login.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        pnl_login.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 111, -1));
        pnl_login.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 111, -1));

        lbl_password.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        lbl_password.setText("Password :");
        pnl_login.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Register ?");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        pnl_login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(102, 0, 102));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        pnl_login.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, -1));

        getContentPane().add(pnl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 330, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        username = usernameTextField.getText();
        password = passwordTextField.getText();
        try{
            sql = "SELECT * FROM user WHERE nama='"+username+"' AND pass='"+password+"'";
            rs = stat.executeQuery(sql);   
            if(rs.next()){
                if(username.equals(rs.getString("nama")) && password.equals(rs.getString("pass"))){
                    JOptionPane.showMessageDialog(null, "berhasil login");
                    user.setId(rs.getInt("id"));
                    user.setNama(rs.getString("nama"));
                    user.setEmail(rs.getString("email"));
                    user.setPass(rs.getString("pass"));
                    user.setStatus(rs.getInt("status"));
                    this.dispose();
                    if(rs.getInt("status") == 1){
                        FormAdmin admin = new FormAdmin(this.user);
                    }else{
                        FormUser user = new FormUser(this.user);
                    }
                }
            }else{
                    JOptionPane.showMessageDialog(null, "wrong username or password");
                }
        }catch (Exception e){
                JOptionPane.showMessageDialog(this, "Failed");
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
     
        this.dispose();
        FormRegister r = new FormRegister();
        r.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
